set_property PACKAGE_PIN W5 [get_ports EXclk]
set_property PACKAGE_PIN R2 [get_ports button]
set_property PACKAGE_PIN A18 [get_ports Tx]
set_property PACKAGE_PIN B18 [get_ports Rx]
set_property IOSTANDARD LVCMOS33 [get_ports EXclk]
set_property IOSTANDARD LVCMOS33 [get_ports button]
set_property IOSTANDARD LVCMOS33 [get_ports Tx]
set_property IOSTANDARD LVCMOS33 [get_ports Rx]

# set_property PACKAGE_PIN L1 [get_ports led]
# set_property IOSTANDARD LVCMOS33 [get_ports led]


set_property PACKAGE_PIN W4 [get_ports {sel[3]}]
set_property PACKAGE_PIN V4 [get_ports {sel[2]}]
set_property PACKAGE_PIN U4 [get_ports {sel[1]}]
set_property PACKAGE_PIN U2 [get_ports {sel[0]}]
set_property PACKAGE_PIN W7 [get_ports {screen_disp[6]}]
set_property PACKAGE_PIN W6 [get_ports {screen_disp[5]}]
set_property PACKAGE_PIN U8 [get_ports {screen_disp[4]}]
set_property PACKAGE_PIN V8 [get_ports {screen_disp[3]}]
set_property PACKAGE_PIN U5 [get_ports {screen_disp[2]}]
set_property PACKAGE_PIN V5 [get_ports {screen_disp[1]}]
set_property PACKAGE_PIN U7 [get_ports {screen_disp[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {screen_disp[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {screen_disp[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {screen_disp[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {screen_disp[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {screen_disp[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {screen_disp[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {screen_disp[0]}]

set_property PACKAGE_PIN U16 [get_ports {leds[0]}]
set_property PACKAGE_PIN E19 [get_ports {leds[1]}]
set_property PACKAGE_PIN U19 [get_ports {leds[2]}]
set_property PACKAGE_PIN V19 [get_ports {leds[3]}]
set_property PACKAGE_PIN W18 [get_ports {leds[4]}]
set_property PACKAGE_PIN U15 [get_ports {leds[5]}]
set_property PACKAGE_PIN U14 [get_ports {leds[6]}]
set_property PACKAGE_PIN V14 [get_ports {leds[7]}]
set_property PACKAGE_PIN V13 [get_ports {leds[8]}]
set_property PACKAGE_PIN V3 [get_ports {leds[9]}]
set_property PACKAGE_PIN W3 [get_ports {leds[10]}]
set_property PACKAGE_PIN U3 [get_ports {leds[11]}]
set_property PACKAGE_PIN P3 [get_ports {leds[12]}]
set_property PACKAGE_PIN N3 [get_ports {leds[13]}]
set_property PACKAGE_PIN P1 [get_ports {leds[14]}]
set_property PACKAGE_PIN L1 [get_ports {leds[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[15]}]

set_property PACKAGE_PIN V17 [get_ports leds_switch]
set_property IOSTANDARD LVCMOS33 [get_ports leds_switch]

